### ISSUE TITLE
TypeError: 'TensorSpec' object is not iterable

### ISSUE THREAD

**Issue by aiporre** [aiporre/multidataloader#7]
Reproduce with:
```python
def read_file(filename):
        return np.zeros(10,10)
 dataset = from_function(read_file, filelist).parallize().parallelize_extraction(num_parallel_calls=2).build()
 list(dataset.as_numpy_iterator())
```

Error
```
Error
Traceback (most recent call last):
  File "/Users/ariel/opt/anaconda3/envs/cellgeo/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/ariel/opt/anaconda3/envs/cellgeo/lib/python3.7/unittest/case.py", line 628, in run
    testMethod()
  File "/Users/ariel/funana/cellgeo/dataset/test_factories.py", line 15, in test_brain_tumor_read_in_parallel
    dataset = dataset_builder.repeat(10).parallelize_extraction(num_parallel_calls=2).build()
  File "/Users/ariel/opt/anaconda3/envs/cellgeo/lib/python3.7/site-packages/dpipe/factories.py", line 132, in parallelize_extraction
    types, shapes = _get_types_output(self.dataset.element_spec)
  File "/Users/ariel/opt/anaconda3/envs/cellgeo/lib/python3.7/site-packages/dpipe/factories.py", line 16, in _get_types_output
    shapes = tuple(e.shape.as_list() for e in element_spec)
TypeError: 'TensorSpec' object is not iterable
```

**Comment by aiporre** [comment]
solution is to change method in line 16 as:
```
shapes = tuple(e.shape.as_list() for e in element_spec) if is_iterable(element_spec) else element_spec.shape.as_list()
types = tuple(e.dtype for e in element_spec) if is_iterable(element_spec) else element_spec.dtype
```
